[package]
name = "ebyte-e32-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ebyte-e32 = "0.3.0"
embedded-hal = "0.2.7"
linux-embedded-hal = "0.3.2"
nb = "1.0.0"
rppal = { version = "0.13.1", features = ["hal", "hal-unproven"] }
